"""empty message

Revision ID: 3a80b32a2fdf
Revises: f00cce651611
Create Date: 2020-06-22 17:34:21.018298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a80b32a2fdf'
down_revision = 'f00cce651611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sede', sa.Column('schedule', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sede', 'schedule')
    # ### end Alembic commands ###
