"""Inicializando DB

Revision ID: 976eefdcd0b0
Revises: 
Create Date: 2020-06-05 18:30:50.916213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976eefdcd0b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disponibilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livroid', sa.Integer(), nullable=True),
    sa.Column('sedeid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('avaliable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novidades',
    sa.Column('content', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('pub_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('content')
    )
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('adrress', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sedes')
    op.drop_table('novidades')
    op.drop_table('livros')
    op.drop_table('disponibilidade')
    # ### end Alembic commands ###
