"""empty message

Revision ID: f00cce651611
Revises: 8ed5e86750e7
Create Date: 2020-06-18 01:11:24.308121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00cce651611'
down_revision = '8ed5e86750e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livro', sa.Column('cover', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livro', 'cover')
    # ### end Alembic commands ###
